### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by Blatts12** [Darkhax-Minecraft/GYTH#1]
Emerald and Obsidian Tanks don't have recipes.

**Comment by darkhax** [comment]
How do you mean, they don't have recipes. For the actual thank itself or for the upgrade item. If you meant the actual tank block, you are only able to craft tier one tanks, the rest have to be achieved through upgrades. If you meant the upgrades, try [these](http://i.imgur.com/AMAMIpN.png) recipes.
