### ISSUE TITLE
[suggestion] can fill bottles directly from tanks

### ISSUE THREAD

**Issue by Prospector** [Darkhax-Minecraft/GYTH#1]
Not sure if this works for water or not, but I know it doesn't work for creosote oil

**Comment by Darkhax** [comment]
Hey there, thank you for the suggestion. I don't believe I have any support for this at the moment however I will look into it when I get a free moment. Should be fairly easy to get this working.

**Comment by Darkhax** [comment]
This should maybe be possible in the 1.10.2 version, depending on how Forge has that set up. I now defer all tank loading and filling logic to forge.
