### ISSUE TITLE
[1.10.2] Major FPS drop attaching Ember Pipes to GYTH tanks

### ISSUE THREAD

**Issue by Morpheus1101** [Darkhax-Minecraft/GYTH#11]
Description sais it all and here is a youtube vid someone has done showcasing the bug in action. Im still waiting on further details to if this occurs with other Fluid Conduits.

https://youtu.be/Qp4vw0SY-B8

**Comment by EliteMasterEric** [comment]
This does not appear to occur with other fluid conduits (it works fine with Fluid Transport Nodes)

**Comment by Darkhax** [comment]
This seems to only be an issue with the ember pipes. Every other pipe or fluid transfer I can think to test with works fine.

**Comment by Darkhax** [comment]
This is almost certainly an issue with the way the embers pipes work. Elucent claims otherwise so I guess there wont be a resolution to this.
