### ISSUE TITLE
Wood tanks all look identical

### ISSUE THREAD

**Issue by VallenFrostweaver** [Darkhax-Minecraft/GYTH#20]
v 2.1.35
Forge 14.23.4.2739
Not sure if it's intended or not but the tier 1 wood tanks all have the oak texture in world but they look different in the UI menu or inventory (acacia has an orange planks texture but I place it and it looks like the oak tank)

**Comment by Darkhax** [comment]
Thanks for the report, I have verified the issue and will put a fix out soon.
