### ISSUE TITLE
[1.7.10] Minetweaker issue

### ISSUE THREAD

**Issue by spannerman79** [Darkhax-Minecraft/GYTH#22]
I took a read of the readme ( https://github.com/Darkhax-Minecraft/GYTH#minetweaker3-support ) and I am using the following to add a Tier 6 tank;

`mods.gyth.Tiers.addTier(bedrockium, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:bedrockiumIngot>, 6);` on the first (and only) line.
I get the following error;
```
ERROR: ?:1 > No such member: gyth
ERROR: GYTH.zs:1 > any values not yet supported
```
gyth has been loaded when I do `/mt mods`;
`GYTH - Get Ya' Tanks Here - 1.1.0`

**Comment by Darkhax** [comment]
CraftTweaker/MineTweaker support was added on Feb 19, 2017. This is several years after the release of 1.7.10. I don't have the resources to maintain feature parity between every version of the game for all of my mods.
