### ISSUE TITLE
Split JEI upgrade entries into separate upgrade tiers

### ISSUE THREAD

**Issue by MatthiasMann** [Darkhax-Minecraft/GYTH#23]
Currently all GYTH upgrade recipes are displayed in one unsorted list in JEI with 8 pages.

It would by nice if the upgrade item had the tier in it's name so that it's easier to search for in JEI and have one page per tier.

I'm using Gyth-1.12.2-2.1.37 and jei_1.12.2-4.15.0.277

**Comment by Darkhax** [comment]
Thanks for the request, I will look into it.
