### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by jdratlif** [Darkhax-Minecraft/GYTH#4]
Wanted to try out this mod, but when I install it, it crashes on game load.

Here is the MultiMC log, the latest.log, and the crash report log:
http://games.technoplaza.net/temp/gyth-crashonload.zip

Minecraft info

version 1.10.2
GYTH 2.0.0.12
Bookshelf 1.4.2.327
Forge 2099

No other mods were installed.

The crash log says something about can't find a class in Bookshelf library. I put all the mods into my mods folder.

**Comment by Darkhax** [comment]
You need to update Bookshelf to a newer version. [This](https://minecraft.curseforge.com/projects/bookshelf/files/2337056) one should work.

**Comment by jdratlif** [comment]
Weird. I was sure I grabbed the latest release version of Bookshelf form Curseforge. Version 330 works. Thanks.
