### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Lorexe** [Darkhax-Minecraft/GYTH#7]
Hello,
I just update Bookshelf to the last version and GYTH crash on startup because of RenderItemEvent doesn't exist anymore.
I know that the version of Bookshelf is an alpha but I prefer report the crash ^^

Crash report : http://pastebin.com/BvuzzvPs

Versions : 
Bookshelf-1.10.2-1.4.4.344
Gyth-1.10.2-2.0.0.23

**Comment by Darkhax** [comment]
The latest version of Bookshelf is in Alpha and should not be used. Please stick to stable releases for Bookshelf.

**Comment by Morpheus1101** [comment]
In this instance i had the same issue and you have to use Bookshelf-1.10.2-1.4.3.340 in order for a Client to load using the latest version of GYTH

**Comment by Baughn** [comment]
To be informative: The latest SkyFactory3 beta release depends on version 345 of Bookshelf, which (naturally, why *wouldn't* it...) crashes in combination with the Get Ya' Tanks Here version they also depend on.

I downgraded to a working version. You might get more people poking around soon, though.

**Comment by Darkhax** [comment]
I specifically told Darkosto in a PM not to use anything above the version he had been using lmao. I guess I will prioritize pushing new stable releases for everything today X)

**Comment by Darkhax** [comment]
@Baughn What is the version number of Sky Factory 3 that you are using? I just downloaded the public beta myself, and they are using 340. I confirmed this with the pack dev that 345 is totally not being used. You sure you downloaded it from the Curse launcher?

**Comment by Baughn** [comment]
Let's see. I don't use the official Curse client (not being on Windows), so it's possible that some difference in the dependency resolution would affect this; if so, I need to fix it.

I've been using Skyfactory-3.0.8. Its manifest.json contains this fragment: `{"fileID":2381531,"projectID":228525,"required":true}`, which refers to https://minecraft.curseforge.com/projects/bookshelf/files/2381531. Version 340, not 345 as I previously incorrectly stated, but still alpha.

Still crashes. The version I'm using, which *doesn't* crash, is 338. Version 340 produced the same error as Lorexe's.

**Comment by Darkhax** [comment]
Fixed, there is now a new latest build for both Bookshelf and GYTH. Please use both.
